on:
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
      tenant:
        description: "GitHub tenant to deploy to (ae / prod)"
        type: string
        required: true
        options:
         - 'ae'
         - 'prod'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
          - 'import'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false
      terraform-import-file:
        description: "(Import only!) <import-file-name>.ps1"
        type: string
        default: ''  
      IsNewDeployment:
        description: "IsNewDeployment?"
        type: boolean
        default: false
        required: true

name: Random ID test

jobs:
  random-id-test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      location: ${{ github.event.inputs.location }}
      tenant: ${{ github.event.inputs.tenant }}
      confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
      IsNewDeployment: ${{ github.event.inputs.IsNewDeployment }}
      terraform-action: ${{ github.event.inputs.terraform-action }}
      terraform-directory: 'random_test'
      terraform-init-args: '-backend-config="key=random_test.tfstate"'
      terraform-plan-args: ''
      terraform-apply-args: ''
      terraform-import-file: ${{ inputs.terraform-import-file }}
    secrets: inherit
