on:
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false

name: Secret test

jobs:
  secret-test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      location: ${{ github.event.inputs.location }}
      confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
      terraform-action: ${{ github.event.inputs.terraform-action }}
      terraform-directory: 'secret-in-reusable'
      terraform-init-args: '-backend-config="key=secret-test.tfstate"'
      terraform-plan-args: '-var shared_key="${VPN_SECRET}"'
      terraform-apply-args: '-var shared_key="${VPN_SECRET}"'
    secrets: inherit
